apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
    name: worker-build
    labels:
        build: worker-build
spec:
    source:
        type: Git
        git:
            uri: 'https://github.com/ihabAbadi/TP'
        contextDir: worker
    strategy:
        type: Docker
        dockerStrategy:
            dockerfilePath: Dockerfile
        pullSecret: "docker"
    output:
        to:
            kind: ImageStreamTag
            name: worker-image:latest
    triggers:
        - type: "GitHub"
          github:
            secretReference:
                name: "mysecret"
        - type: ConfigChange     